<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>strong_automation</name>
   <tag></tag>
   <elementGuidId>31f07103-7c2c-48b6-8b88-530fcc3a9be7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='udemy']/div[2]/div[2]/div/div[2]/div[3]/div/div/div/ul/li/a/span/span[2]/strong</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>strong</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>automation</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;udemy&quot;)/div[@class=&quot;main-content-wrapper&quot;]/div[@class=&quot;c_header c_header--v6 c_header--desktop c_header--ia c_header--ia- ud-app-loader ud-app-loaded&quot;]/div[@class=&quot;c_header__inner&quot;]/div[@class=&quot;c_header__left&quot;]/div[@class=&quot;c_header__search-wrapper ud-component--header-v6--header-es-autocomplete&quot;]/div[@class=&quot;c_header__search&quot;]/div[@class=&quot;c_quick-search__form pos-r&quot;]/div[@class=&quot;dropdown es-autocomplete open es-autocomplete--primary&quot;]/ul[@class=&quot;dropdown-menu&quot;]/li[1]/a[1]/span[@class=&quot;ellipsis&quot;]/span[2]/strong[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='udemy']/div[2]/div[2]/div/div[2]/div[3]/div/div/div/ul/li/a/span/span[2]/strong</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search for anything'])[1]/following::strong[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='testing'])[1]/preceding::strong[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//strong</value>
   </webElementXpaths>
</WebElementEntity>
